### ISSUE TITLE
REPL not working correctly

### ISSUE THREAD

**Issue by ajs-amandasmith** [learn-co-curriculum/phase-0-pac-1-intro#13]
### Canvas Link

https://learning.flatironschool.com/courses/4976/pages/introduction-to-programming-as-conversation?module_item_id=345680

### Concern

In the two REPLs where you push the green "play" button to get a correct return value, nothing is returned. The 1 + 1 and the 1 + "Cookie Monster". In the return field it only says "Hint: hit control+c anytime to enter REPL" after hitting the "play"
<img width="659" alt="Screen Shot 2022-02-03 at 1 36 25 PM" src="https://user-images.githubusercontent.com/37988788/152416282-f9e5180e-03cb-4084-89de-92a4cda1af16.png">

**Comment by lizbur10** [comment]
Hi @ajs-amandasmith ! Thanks for bringing this to our attention.

We are aware of the problem and are working on a fix, but it will likely take a bit of time to resolve. In the meantime, as a workaround, you can type or copy/paste code directly into the console window and press enter.

Apologies for the inconvenience! 

Thanks for contributing to the Flatiron School curriculum! 💙
