### ISSUE TITLE
JavaScript Replit examples showing blank output

### ISSUE THREAD

**Issue by beckharper** [learn-co-curriculum/phase-0-pac-1-intro#14]
### Canvas Link

https://learning.flatironschool.com/courses/5470/pages/introduction-to-programming-as-conversation?module_item_id=363159

### Concern

The second two JavaScript examples (1 + 1 and 1 + "Cookie Monster") are showing blank outputs via Replit. 
![Screen Recording 2022-02-09 at 12 58 41](https://user-images.githubusercontent.com/93853978/153289702-bf68796e-5a13-4a25-801b-f2c82d78469d.gif)

**Comment by beckharper** [comment]
Already addressed in another issue

**Comment by lizbur10** [comment]
Sorry for the inconvenience, @nicholashale ! And thanks for contributing to the Flatiron School curriculum 💙
