### ISSUE TITLE
Replit embed broken again

### ISSUE THREAD

**Issue by CodeF53** [learn-co-curriculum/phase-0-pac-1-intro#15]
### Canvas Link

https://learning.flatironschool.com/courses/5797/pages/introduction-to-programming-as-conversation?module_item_id=413703

### Concern

The replit embed for a javascript console displays an error 404.
![image](https://user-images.githubusercontent.com/37855219/175341527-7107e79e-2cff-4946-9154-3cc54fceb74b.png)

### Possibly relevant info:

 - Firefox 101 
 - Windows 10
 - Javascript Enabled
 - 3rd party cookies Enabled

**Comment by CodeF53** [comment]
Issue also applies to the following lessons:

https://learning.flatironschool.com/courses/5797/pages/expressions-in-javascript?module_item_id=413704
https://github.com/learn-co-curriculum/phase-0-pac-1-expressions-in-js

https://learning.flatironschool.com/courses/5797/pages/the-constant-expression?module_item_id=413705
https://github.com/learn-co-curriculum/phase-0-pac-1-the-constant-expression

https://learning.flatironschool.com/courses/5797/pages/the-assignment-expression?module_item_id=413706
https://github.com/learn-co-curriculum/phase-0-pac-1-the-assignment-expression

https://learning.flatironschool.com/courses/5797/pages/the-variable-lookup-expression?module_item_id=413707
https://github.com/learn-co-curriculum/phase-0-pac-1-the-variable-lookup-expression

https://learning.flatironschool.com/courses/5797/pages/logical-operators?module_item_id=413713
https://github.com/learn-co-curriculum/phase-0-pac-1-logical-operators

**Comment by lizbur10** [comment]
Hi @CodeF53 ! Thanks for bringing this to our attention - the issue should now be fixed. 💙
