### ISSUE TITLE
no images

### ISSUE THREAD

**Issue by ethanfree23** [learn-co-curriculum/phase-0-pac-1-intro#4]
### Canvas Link

https://learning.flatironschool.com/courses/4837/pages/introduction-to-programming-as-conversation?module_item_id=305150

### Concern

images do not show

**Comment by lizbur10** [comment]
Hi @ethanfree23 ! I am not able to recreate the issue - the images are showing up for me. Hopefully it was just a temporary service issue. 

I'm going to go ahead and close this issue, but if you're continuing to have the problem feel free to reopen it. 💙
