### ISSUE TITLE
Issue with 'Introduction to Programming as Conversation' page. 

### ISSUE THREAD

**Issue by veritycarlos** [learn-co-curriculum/phase-0-pac-1-intro#6]
### Canvas Link

https://learning.flatironschool.com/courses/4968/pages/introduction-to-programming-as-conversation?module_item_id=321628

### Concern

The first Javascript index box is returning an error message when I hit run, as it's supposed to, but the second, and third are not doing anything when I hit run. 

### Additional Context

The second and third boxes say "Hint: hit control+c anytime to enter REPL." when I hit run. I tried to click in the box to see if I needed to type something, and when I did I was prompted to create an account with REPL, so I did, but after I made the account and refreshed the page a few times it still gave the same error message.

![intro javas conv error 1-27-2022](https://user-images.githubusercontent.com/97711084/151434344-aeabccc0-1fb5-4a5f-a795-78491e3b68dc.png)

**Comment by lizbur10** [comment]
Hi @veritycarlos! Thank you for bringing this to our attention. We are aware of the issue and are working on resolving it. In the meantime, you can type or copy/paste the code directly into the console (the bottom window) and hit enter to run the code. You'll need to do this for any lessons that include the embedded repl's.

Apologies for the inconvenience! 💙

**Comment by veritycarlos** [comment]
Thank you! This was very helpful.

**Comment by lizbur10** [comment]
Hi @veritycarlos ! The updates to the prework lessons and labs that use replit have been completed. Note that, depending on when you were assigned to a prework course, the changes may not be reflected in your Canvas lessons. Our apologies for any inconvenience this causes you.

Thanks again for contributing 💙
