### ISSUE TITLE
Replit example not populating in console when running code 1 + 1 & 1 + "Cookie monster"

### ISSUE THREAD

**Issue by Hamernick** [learn-co-curriculum/phase-0-pac-1-intro#7]
### Canvas Link

https://learning.flatironschool.com/courses/5461/pages/introduction-to-programming-as-conversation?module_item_id=353229

### Concern

Introduction to programming as a conversation - the replit examples don't do anything when you run the programs.

**Comment by lizbur10** [comment]
Hi @Hamernick ! Thanks for bringing this to our attention. We are aware of the problem and are working on a solution, but it may take a while to resolve. In the meantime, as a work-around, you can type or copy/paste code into the console window and hit enter.

Thanks for contributing to the Flatiron School curriculum 💙

**Comment by lizbur10** [comment]
Hi @Hamernick  ! The updates to the prework lessons and labs that use replit have been completed. Note that, depending on when you were assigned to a prework course, the changes may not be reflected in your Canvas lessons. Our apologies for any inconvenience this causes you.

Thanks again for contributing 💙
